[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/records"
  to = "/.netlify/functions/records"
  status = 200

[[redirects]]
  from = "/api/earnings"
  to = "/.netlify/functions/earnings"
  status = 200