services:
  - type: web
    name: daily-spending
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_CREDENTIALS_B64
        sync: false